---
title: "Welcoming words"
author: "Olivier Gimenez & Daniel Turek"
date: "last updated: `r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: [default, "slides-theme.css"]
    lib_dir: libs
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      slideNumberFormat: ''
      titleSlideClass: [center, middle]
---

```{r setup, include=FALSE, echo=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(comment = "")

library(tidyverse)
theme_set(theme_light())
update_geom_defaults("point", list(size = 2)) 
library(here)
library(nimble)
```

## What this workshop is about

???

+ So why are we here altogether? 

--

+ Estimating demographic parameters with capture-recapture.

???

+ Well this is a workshop about the estimation of demographic parameters, like survival, recruitment or dispersal. 
+ To do so, we will use capture-recapture data. 

--

+ Using a family of models called hidden Markov models (HMM).

???

+ We will use a family of models called hidden Markov models (HMMs in short).
+ Why? Because HMMs are quite awesome as we will see, because with the same model structure we'll be able to fit all sorts of capture-recapture models and estimate key demographic parameters. 

--

+ Within the Bayesian framework implemented with Markov chain Monte Carlo methods (MCMC).

???

+ We'll work within the Bayesian framework for many reasons we will develop, but mainly because Bayesian statistics make it easy to manage uncertainty, and also because with MCMC, we can fit pretty much fit any models. 

---
## On our plate

???

+ OK, what's on our plate? 

--

+ What you see is not what you get: Hidden Markov models and capture-recapture data (9:00am-9:45am) - Olivier

???

+ First things first, we'll go through an introduction to hidden Markov models. 
+ We'll talk about survival models.

--

+ On the move: Transition estimation (10:00am-10:45am) - Daniel

???

+ And models to estimate transition between states.
+ Geographical sites or breeding states for example.

--

+ Known knowns, unknown knowns and unknowns: Uncertainty in state assignment (11:00am-11:45am) - Olivier

???

+ Then it will be about more advanced stuff. 
+ How to account for uncertainty in the assignment of these states to individuals. 

--

+ Skip your coffee break: Speed up MCMC convergence (noon-12:45pm) - Daniel

???

+ Also how to save time when running long analyses on your computer. 

---
## Philosophy of teaching

???

+ Before we start, a few words about our teaching philosophy. 

--

+ You're 44 attendees, with some heterogeneity in knowledge of capture-recapture models, Bayesian methods, `R` and `Nimble`.

???

+ You'll be 44 folks attending today, there is heterogeneity in knowledge of the methods we will cover. 

--

+ It is our hope that everyone will find something to take home. 

???

+ It is our hope however that everyone will find something to take home. 

--

+ We've packed a lot of things half a day.

???

+ We'll be covering a lot of things in half a day. 

--

+ We do not expect you to digest everything.

???

+ Do not feel like you have to fully understand everything at once. 
+ Took us years to be comfortable with the material we will cover. 

--

+ All material (including videos) on website <https://oliviergimenez.github.io/hmm-cr-nimble-isec2022-workshop/>.

???

+ To help, we have made all material available on a website. 
+ Let's take a minute to have a look to the website.


--

+ Feel free to play around with material while we walk through it, and afterwards.

???

+ Feel free to play around with the material we provide. 

--

+ The workshop is organized in modules, each module is a combination of lectures and live demos.

???

+ We will have lectures, and live demos. 

---

## The way we will interact with each other

--

+ Lectures and live coding demos will happen in Zoom.

???

+ Lectures and live demos will happen in Zoom. 
+ We will use the same link for both days. 

--

+ Everything is video recorded.

???

+ Everything is video recorded.
+ The recordings will be made available on the website. 

--

+ Questions and answers via Zoom.

???

+ Feel free to ask questions. We'll do our best to answer live or soon after the workshop. 
